name: Docker builds

on:
  push:
    branches:
      - "main"

jobs:
  build-push-academy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.0

      - name: Set outputs
        id: vars
        run: |
          echo "::set-output name=date::$(date +%Y-%m-%dT%H-%M-%S)"
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - name: Set up Docker Buildx
        uses: docker/Setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: docker/build-push-action@v3
        with:
          file: "./Dockerfile"
          context: .
          # Only push when on main
          push: ${{ github.ref == 'refs/heads/main' && github.event_name == 'push' }}
          tags: |
            ghcr.io/ligolang/academy:latest
            ghcr.io/ligolang/academy:${{ steps.vars.outputs.date }}-${{ steps.vars.outputs.sha_short }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
